version: '3.1'

services:
  api:
    container_name: api
    image: node:10-slim
    volumes:
      - ./:/data/vhosts/api
    working_dir: /data/vhosts/api
    command: tail -f /dev/null
    ports:
      - 3000:3000
    networks:
      - mongo-cluster

  mongo1:
    container_name: mongo1
    image: mongo
    volumes:
      - ./docker:/data/vhosts/api/docker
    command: bash -c "/data/vhosts/api/docker/init_replica_set.sh"
    ports:
      - 30001:30001
    networks:
      - mongo-cluster

  mongo2:
    container_name: mongo2
    image: mongo
    command: "mongod --port 30002 --replSet my-mongo-set --bind_ip_all"
    ports:
      - 30002:30002
    networks:
      - mongo-cluster

  mongo3:
    container_name: mongo3
    image: mongo
    command: "mongod --port 30003 --replSet my-mongo-set --bind_ip_all"
    ports:
      - 30003:30003
    networks:
      - mongo-cluster

networks:
  mongo-cluster:
