version: '3.1'

services:
  mongo1:
    container_name: mongo1
    image: mongo
    command: "mongod --port 30001 --replSet my-mongo-set"
    ports:
      - 30001:30001
    networks:
      - mongo-cluster

  mongo2:
    container_name: mongo2
    image: mongo
    command: "mongod --port 30002 --replSet my-mongo-set"
    ports:
      - 30002:30002
    networks:
      - mongo-cluster

  mongo3:
    container_name: mongo3
    image: mongo
    command: "mongod --port 30003 --replSet my-mongo-set"
    ports:
      - 30003:30003
    networks:
      - mongo-cluster

networks:
  mongo-cluster:
