version: '3.1'

networks:
  mongo-cluster:

services:
  mds-api:
    container_name: mds-api
    #build:
    #  context: ./
    #  dockerfile: Dockerfile.prod
    image: tngsy/mds-mongodb-nodejs_mds-api:latest
    environment:
      - API_PORT=3000
      - API_ENV=prod
      - PROD_MONGO_CONNECTION_STRING=mongodb://mongo1:30001,mongo2:30002,mongo3:30003/test?replicaSet=my-mongo-set
    ports:
      - 3000:3000
    networks:
      - mongo-cluster
    depends_on:
      - mongo1

  mongo1:
    container_name: mongo1
    image: mongo
    working_dir: /mongo
    volumes:
      - ./mongo_log/mongo1:/mongo
      - ./init_replica_set.sh:/db/init_replica_set.sh
    command: bash -c "/db/init_replica_set.sh"
    ports:
      - 30001:30001
    networks:
      - mongo-cluster
    depends_on:
      - mongo2
      - mongo3

  mongo2:
    container_name: mongo2
    image: mongo
    working_dir: /mongo
    volumes:
      - ./mongo_log/mongo2:/mongo
    command: "mongod --port 30002 --replSet my-mongo-set --bind_ip_all --logpath mongo.log"
    ports:
      - 30002:30002
    networks:
      - mongo-cluster

  mongo3:
    container_name: mongo3
    image: mongo
    working_dir: /mongo
    volumes:
      - ./mongo_log/mongo3:/mongo
    command: "mongod --port 30003 --replSet my-mongo-set --bind_ip_all --logpath mongo.log"
    ports:
      - 30003:30003
    networks:
      - mongo-cluster
