version: '3.1'

networks:
  mongo-cluster:

services:
  mds-api:
    container_name: mds-api
    build:
      context: ./docker/app
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    command: npm run run-local
    ports:
      - 3000:3000
    networks:
      - mongo-cluster
    depends_on:
      - mongo1
      - mongo2
      - mongo3

  mongo1:
    container_name: mongo1
    image: mongo
    volumes:
      - ./docker/database://docker/database
      - ./dblog:/var/log/mongodb
    command: bash -c "/docker/database/init_replica_set.sh"
    ports:
      - 30001:30001
    networks:
      - mongo-cluster

  mongo2:
    container_name: mongo2
    image: mongo
    command: "mongod --port 30002 --replSet my-mongo-set --bind_ip_all"
    volumes:
      - ./dblog:/var/log/mongodb
    ports:
      - 30002:30002
    networks:
      - mongo-cluster

  mongo3:
    container_name: mongo3
    image: mongo
    command: "mongod --port 30003 --replSet my-mongo-set --bind_ip_all"
    volumes:
      - ./dblog:/var/log/mongodb
    ports:
      - 30003:30003
    networks:
      - mongo-cluster
